/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as MetodosRouteImport } from './routes/metodos'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ChannelChannelIdIndexRouteImport } from './routes/channel.$channelId.index'
import { Route as ChannelChannelIdLibraryRouteImport } from './routes/channel.$channelId.library'
import { Route as ChannelChannelIdMethodsRouteImport } from './routes/channel.$channelId.methods'
import { Route as ChannelChannelIdResearchRouteImport } from './routes/channel.$channelId.research'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId.index'
import { Route as ProjectProjectIdAssetsRouteImport } from './routes/project.$projectId.assets'
import { Route as ProjectProjectIdEditRouteImport } from './routes/project.$projectId.edit'
import { Route as ProjectProjectIdNarrationRouteImport } from './routes/project.$projectId.narration'
import { Route as ProjectProjectIdPublishRouteImport } from './routes/project.$projectId.publish'
import { Route as ProjectProjectIdScriptRouteImport } from './routes/project.$projectId.script'
import { Route as ProjectProjectIdThemeRouteImport } from './routes/project.$projectId.theme'
import { Route as ProjectProjectIdThumbnailRouteImport } from './routes/project.$projectId.thumbnail'
import { Route as ProjectProjectIdTitleRouteImport } from './routes/project.$projectId.title'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodosRoute = MetodosRouteImport.update({
  id: '/metodos',
  path: '/metodos',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdIndexRoute = ChannelChannelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdLibraryRoute = ChannelChannelIdLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdMethodsRoute = ChannelChannelIdMethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => ChannelChannelIdRoute,
} as any)
const ChannelChannelIdResearchRoute =
  ChannelChannelIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => ChannelChannelIdRoute,
  } as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdAssetsRoute = ProjectProjectIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdEditRoute = ProjectProjectIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdNarrationRoute =
  ProjectProjectIdNarrationRouteImport.update({
    id: '/narration',
    path: '/narration',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdPublishRoute = ProjectProjectIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdScriptRoute = ProjectProjectIdScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdThemeRoute = ProjectProjectIdThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdThumbnailRoute =
  ProjectProjectIdThumbnailRouteImport.update({
    id: '/thumbnail',
    path: '/thumbnail',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdTitleRoute = ProjectProjectIdTitleRouteImport.update({
  id: '/title',
  path: '/title',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/methods': typeof MethodsRoute
  '/metodos': typeof MetodosRoute
  '/plugins': typeof PluginsRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/channel/$channelId/library': typeof ChannelChannelIdLibraryRoute
  '/channel/$channelId/methods': typeof ChannelChannelIdMethodsRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/project/$projectId/assets': typeof ProjectProjectIdAssetsRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/narration': typeof ProjectProjectIdNarrationRoute
  '/project/$projectId/publish': typeof ProjectProjectIdPublishRoute
  '/project/$projectId/script': typeof ProjectProjectIdScriptRoute
  '/project/$projectId/theme': typeof ProjectProjectIdThemeRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/title': typeof ProjectProjectIdTitleRoute
  '/channel/$channelId/': typeof ChannelChannelIdIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/methods': typeof MethodsRoute
  '/metodos': typeof MetodosRoute
  '/plugins': typeof PluginsRoute
  '/channel/$channelId/library': typeof ChannelChannelIdLibraryRoute
  '/channel/$channelId/methods': typeof ChannelChannelIdMethodsRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/project/$projectId/assets': typeof ProjectProjectIdAssetsRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/narration': typeof ProjectProjectIdNarrationRoute
  '/project/$projectId/publish': typeof ProjectProjectIdPublishRoute
  '/project/$projectId/script': typeof ProjectProjectIdScriptRoute
  '/project/$projectId/theme': typeof ProjectProjectIdThemeRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/title': typeof ProjectProjectIdTitleRoute
  '/channel/$channelId': typeof ChannelChannelIdIndexRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/methods': typeof MethodsRoute
  '/metodos': typeof MetodosRoute
  '/plugins': typeof PluginsRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/channel/$channelId/library': typeof ChannelChannelIdLibraryRoute
  '/channel/$channelId/methods': typeof ChannelChannelIdMethodsRoute
  '/channel/$channelId/research': typeof ChannelChannelIdResearchRoute
  '/project/$projectId/assets': typeof ProjectProjectIdAssetsRoute
  '/project/$projectId/edit': typeof ProjectProjectIdEditRoute
  '/project/$projectId/narration': typeof ProjectProjectIdNarrationRoute
  '/project/$projectId/publish': typeof ProjectProjectIdPublishRoute
  '/project/$projectId/script': typeof ProjectProjectIdScriptRoute
  '/project/$projectId/theme': typeof ProjectProjectIdThemeRoute
  '/project/$projectId/thumbnail': typeof ProjectProjectIdThumbnailRoute
  '/project/$projectId/title': typeof ProjectProjectIdTitleRoute
  '/channel/$channelId/': typeof ChannelChannelIdIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/methods'
    | '/metodos'
    | '/plugins'
    | '/channel/$channelId'
    | '/project/$projectId'
    | '/channel/$channelId/library'
    | '/channel/$channelId/methods'
    | '/channel/$channelId/research'
    | '/project/$projectId/assets'
    | '/project/$projectId/edit'
    | '/project/$projectId/narration'
    | '/project/$projectId/publish'
    | '/project/$projectId/script'
    | '/project/$projectId/theme'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/title'
    | '/channel/$channelId/'
    | '/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/methods'
    | '/metodos'
    | '/plugins'
    | '/channel/$channelId/library'
    | '/channel/$channelId/methods'
    | '/channel/$channelId/research'
    | '/project/$projectId/assets'
    | '/project/$projectId/edit'
    | '/project/$projectId/narration'
    | '/project/$projectId/publish'
    | '/project/$projectId/script'
    | '/project/$projectId/theme'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/title'
    | '/channel/$channelId'
    | '/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/methods'
    | '/metodos'
    | '/plugins'
    | '/channel/$channelId'
    | '/project/$projectId'
    | '/channel/$channelId/library'
    | '/channel/$channelId/methods'
    | '/channel/$channelId/research'
    | '/project/$projectId/assets'
    | '/project/$projectId/edit'
    | '/project/$projectId/narration'
    | '/project/$projectId/publish'
    | '/project/$projectId/script'
    | '/project/$projectId/theme'
    | '/project/$projectId/thumbnail'
    | '/project/$projectId/title'
    | '/channel/$channelId/'
    | '/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MethodsRoute: typeof MethodsRoute
  MetodosRoute: typeof MetodosRoute
  PluginsRoute: typeof PluginsRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRouteWithChildren
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodos': {
      id: '/metodos'
      path: '/metodos'
      fullPath: '/metodos'
      preLoaderRoute: typeof MetodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/': {
      id: '/channel/$channelId/'
      path: '/'
      fullPath: '/channel/$channelId/'
      preLoaderRoute: typeof ChannelChannelIdIndexRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/library': {
      id: '/channel/$channelId/library'
      path: '/library'
      fullPath: '/channel/$channelId/library'
      preLoaderRoute: typeof ChannelChannelIdLibraryRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/methods': {
      id: '/channel/$channelId/methods'
      path: '/methods'
      fullPath: '/channel/$channelId/methods'
      preLoaderRoute: typeof ChannelChannelIdMethodsRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/channel/$channelId/research': {
      id: '/channel/$channelId/research'
      path: '/research'
      fullPath: '/channel/$channelId/research'
      preLoaderRoute: typeof ChannelChannelIdResearchRouteImport
      parentRoute: typeof ChannelChannelIdRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/assets': {
      id: '/project/$projectId/assets'
      path: '/assets'
      fullPath: '/project/$projectId/assets'
      preLoaderRoute: typeof ProjectProjectIdAssetsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/edit': {
      id: '/project/$projectId/edit'
      path: '/edit'
      fullPath: '/project/$projectId/edit'
      preLoaderRoute: typeof ProjectProjectIdEditRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/narration': {
      id: '/project/$projectId/narration'
      path: '/narration'
      fullPath: '/project/$projectId/narration'
      preLoaderRoute: typeof ProjectProjectIdNarrationRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/publish': {
      id: '/project/$projectId/publish'
      path: '/publish'
      fullPath: '/project/$projectId/publish'
      preLoaderRoute: typeof ProjectProjectIdPublishRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/script': {
      id: '/project/$projectId/script'
      path: '/script'
      fullPath: '/project/$projectId/script'
      preLoaderRoute: typeof ProjectProjectIdScriptRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/theme': {
      id: '/project/$projectId/theme'
      path: '/theme'
      fullPath: '/project/$projectId/theme'
      preLoaderRoute: typeof ProjectProjectIdThemeRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/thumbnail': {
      id: '/project/$projectId/thumbnail'
      path: '/thumbnail'
      fullPath: '/project/$projectId/thumbnail'
      preLoaderRoute: typeof ProjectProjectIdThumbnailRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/title': {
      id: '/project/$projectId/title'
      path: '/title'
      fullPath: '/project/$projectId/title'
      preLoaderRoute: typeof ProjectProjectIdTitleRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ChannelChannelIdRouteChildren {
  ChannelChannelIdLibraryRoute: typeof ChannelChannelIdLibraryRoute
  ChannelChannelIdMethodsRoute: typeof ChannelChannelIdMethodsRoute
  ChannelChannelIdResearchRoute: typeof ChannelChannelIdResearchRoute
  ChannelChannelIdIndexRoute: typeof ChannelChannelIdIndexRoute
}

const ChannelChannelIdRouteChildren: ChannelChannelIdRouteChildren = {
  ChannelChannelIdLibraryRoute: ChannelChannelIdLibraryRoute,
  ChannelChannelIdMethodsRoute: ChannelChannelIdMethodsRoute,
  ChannelChannelIdResearchRoute: ChannelChannelIdResearchRoute,
  ChannelChannelIdIndexRoute: ChannelChannelIdIndexRoute,
}

const ChannelChannelIdRouteWithChildren =
  ChannelChannelIdRoute._addFileChildren(ChannelChannelIdRouteChildren)

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdAssetsRoute: typeof ProjectProjectIdAssetsRoute
  ProjectProjectIdEditRoute: typeof ProjectProjectIdEditRoute
  ProjectProjectIdNarrationRoute: typeof ProjectProjectIdNarrationRoute
  ProjectProjectIdPublishRoute: typeof ProjectProjectIdPublishRoute
  ProjectProjectIdScriptRoute: typeof ProjectProjectIdScriptRoute
  ProjectProjectIdThemeRoute: typeof ProjectProjectIdThemeRoute
  ProjectProjectIdThumbnailRoute: typeof ProjectProjectIdThumbnailRoute
  ProjectProjectIdTitleRoute: typeof ProjectProjectIdTitleRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdAssetsRoute: ProjectProjectIdAssetsRoute,
  ProjectProjectIdEditRoute: ProjectProjectIdEditRoute,
  ProjectProjectIdNarrationRoute: ProjectProjectIdNarrationRoute,
  ProjectProjectIdPublishRoute: ProjectProjectIdPublishRoute,
  ProjectProjectIdScriptRoute: ProjectProjectIdScriptRoute,
  ProjectProjectIdThemeRoute: ProjectProjectIdThemeRoute,
  ProjectProjectIdThumbnailRoute: ProjectProjectIdThumbnailRoute,
  ProjectProjectIdTitleRoute: ProjectProjectIdTitleRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MethodsRoute: MethodsRoute,
  MetodosRoute: MetodosRoute,
  PluginsRoute: PluginsRoute,
  ChannelChannelIdRoute: ChannelChannelIdRouteWithChildren,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
